language: node_js
node_js:
  - "node"
cache:
  directories:
    - library/node_modules
    - builder/node_modules
install:
  - (cd library && npm install)
  - (cd builder && npm install)
script:
  - (cd library && npm run build:starterkit)
  - (cd builder && npm run build)
  - (cd builder && npm run test)
