language: node_js
dist: trusty
sudo: false
addons:
  chrome: stable
node_js:
  - "node"
git:
  depth: 10
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm run bootstrap
script:
  - (cd packages/library && npm run build:starterkit)
  - (cd packages/library && npm test)
  - (cd packages/builder && npm run build)
  - (cd packages/builder && npm test)
