language: node_js
dist: trusty
sudo: required
addons:
  chrome: stable
  sauce_connect: true
node_js:
  - "node"
git:
  depth: 10
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - yarn run bootstrap
script:
  - (cd packages/library && yarn run build:starterkit)
  - (cd packages/library && yarn test)
  - (cd packages/library && yarn run test:sauce)
  - (cd packages/builder && yarn run build)
  - (cd packages/builder && yarn test)
after_success:
  - (cd packages/builder && yarn run deploy)
